BasketBallMVC/BasketBallMVC/Controllers/CharacterController.cs
using BasketBallMVC.Services;
using BasketBallMVC.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PagedList;
using Newtonsoft.Json;
using BasketBallMVC.Hubs;

namespace BasketBallMVC.Controllers
{
    [Authorize]
    public class CharacterController : Controller
    {
        private UserService _userService = new UserService();
        private ComplementViewModelsService _complementVMService = new ComplementViewModelsService();
        private FriendService _friendService = new FriendService();
        private NotificationService _notificationService = new NotificationService();
        // GET: Character
        public ActionResult FriendsList(int? Page)
        {
            int page = Page ?? 1;
            FriendsListViewModel firendsVM = _complementVMService.ComplementFriendsListVM();

            if (firendsVM.CharacterForFriendList != null)
            {
                firendsVM.CharacterForFriendList =  firendsVM.CharacterForFriendList.OrderBy(x => x.Nick).ToList();
                firendsVM.CharacterForFriendListPaged = firendsVM.CharacterForFriendList.ToPagedList(page, 11);
            }

            return View(firendsVM);
        }

        public ActionResult Ranking(int? Page, string searchString)
        {
            int page = Page ?? 1;
            RankingViewModel rankingVM = _complementVMService.ComplementRankingVM();

            if (rankingVM.CharacterForRanking != null)
            {
                if (!string.IsNullOrEmpty(searchString))
                {
                    rankingVM.CharacterForRanking = rankingVM.CharacterForRanking.Where(s => s.Nick.Contains(searchString)).ToList();
                }
                rankingVM.CharacterForRanking = rankingVM.CharacterForRanking.OrderByDescending(x => x.TotalPoints).ToList();
                rankingVM.CharacterForRankingPaged = rankingVM.CharacterForRanking.ToPagedList(page, 11);
            }
            return View(rankingVM);
        }
        public JsonResult CreateFriendInvitation(string invitedEmail)
        {
            var AllCurrentUserFriendInvitation = _userService.GetCurrentUserAllFriendInvitation();
            var AllCurrentUserFriends = _userService.GetCurrentUserAllFriends();
            var result = _friendService.InviteFriend(AllCurrentUserFriendInvitation, AllCurrentUserFriends, invitedEmail);
            Dictionary<string, string> dictionaryResult = new Dictionary<string, string>();

            string json = string.Empty;

            switch (result)
            {
                case "UserException":
                    dictionaryResult.Add("status", "UserException");
                    break;
                case "InvitationException":
                    dictionaryResult.Add("status", "InvitationException");
                    break;
                case "FriendException":
                    dictionaryResult.Add("status", "FriendException");
                    break;
                case "Success":
                    dictionaryResult.Add("status", "Success");
                    _notificationService.AddInviteNotification(invitedEmail, User.Identity.Name);
                    NotificationHub.AddNotification(invitedEmail);
                    break;
                case "SelfException":
                    dictionaryResult.Add("status", "SelfException");
                    break;
            }
            json = JsonConvert.SerializeObject(dictionaryResult);

            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public void RemoveFriend(string friendNick)
        {
            _friendService.RemoveFriend(friendNick);
        }
       
        public ActionResult CharacterProfil(string nick)
        {
            var userId = _userService.GetUserIdByNick(nick);
            CharacterProfilViewModel characterProfileVM = _complementVMService.ComplementCharacterProfilVM(userId);
            
            return View(characterProfileVM);
        }
    }
}

BasketBallMVC/BasketBallMVC/Controllers/CityController.cs
using BasketBallMVC.Services;
using BasketBallMVC.ViewModel;
using System.Web.Mvc;

namespace BasketBallMVC.Controllers
{
    [Authorize]
    public class CityController : Controller
    {
        private ComplementViewModelsService _complementVMService = new ComplementViewModelsService();
        private RestaurantService _restaurantService = new RestaurantService();
        private ShopService _shopService = new ShopService();
        

        public ActionResult Shop()
        {
            ShopViewModel shopVM = _complementVMService.ComplementShopVM();
            
            return View(shopVM);
        }

        public JsonResult GetCtegoriesForShop(string buttonId)
        {
            string json = _shopService.GetCategoriesForShop(buttonId);

            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public JsonResult BuyNewDevice(string buttonId)
        {
            string json = _shopService.BuyNewDevice(buttonId);

            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public void SaleDevice(string buttonId)
        {
            _shopService.SaleDevice(buttonId);
        }

        public ActionResult Restaurant()
        {
            RestaurantViewModel restaurantVM = _complementVMService.ComplementRestaurantVM();

            return View(restaurantVM);
        }

        public void BuyFood(string btnId, string size)
        {
            _restaurantService.BuyFood(btnId, size);
        }
    }
}

BasketBallMVC/BasketBallMVC/Controllers/GameController.cs
using BasketBallMVC.Hubs;
using BasketBallMVC.Services;
using BasketBallMVC.ViewModel;
using System.Web.Mvc;

namespace BasketBallMVC.Controllers
{
    [Authorize]
    public class GameController : Controller
    {
        private UserService _userService = new UserService();
        private BattleService _battleService = new BattleService();
        private ComplementViewModelsService _complementVMService = new ComplementViewModelsService();
        private TrainingRoomService _trainingRoomService = new TrainingRoomService();
        private CharacterService _characterService = new CharacterService();
        private NotificationService _notificationService = new NotificationService();
        // GET: Game
        public ActionResult Battle()
        {
            BattleViewModel battleVM = _complementVMService.ComplementBattleVM();
            _battleService.CheckChosenAttacks(ref battleVM);


            return View(battleVM);
        }
        public ActionResult VsComputer()
        {
            var tuple = _characterService.CheckLifeAndEnergy();
            BattleViewModel battleVM = _complementVMService.ComplementBattleVM();
            _battleService.CheckChosenAttacks(ref battleVM);
            if (tuple.Item1 && tuple.Item2 && battleVM.isAttacksChosen)
            {
                var listOfAttacks = _battleService.GenerateBattleVsComputer();
                var battleLog = _battleService.GenerateBattleText(listOfAttacks);
                _characterService.ChangeStats(battleLog, true, string.Empty);

                _complementVMService.UpdateBattleVM(ref battleVM);
                battleVM.PlayerResult = int.Parse(battleLog[battleLog.Count - 1].leftSum);
                battleVM.OponentResult = int.Parse(battleLog[battleLog.Count - 1].rightSum);
                battleVM.OponentNick = "Komputer";
                battleVM.PlayerNick = _userService.GetUserNickByIdentityName();

                battleVM.battleLog = battleLog;
            }
            if (tuple.Item1)
                battleVM.isEnoughLife = true;
            else
                battleVM.isEnoughLife = false;

            if (tuple.Item2)
                battleVM.isEnoughEnergy = true;
            else
                battleVM.isEnoughEnergy = false;


            return View("Battle", battleVM);
        }
        public ActionResult VsRandomPlayer()
        {
            var tuple = _characterService.CheckLifeAndEnergy();
            BattleViewModel battleVM = _complementVMService.ComplementBattleVM();
            _battleService.CheckChosenAttacks(ref battleVM);

            if (tuple.Item1 && tuple.Item2 && battleVM.isAttacksChosen)
            {
                var oponentId = _battleService.SearchOponent();

                var listOfAttacks = _battleService.BattleVsPlayer(oponentId);
                var battleLog = _battleService.GenerateBattleText(listOfAttacks);
                _characterService.ChangeStats(battleLog, false, oponentId);

                _complementVMService.UpdateBattleVM(ref battleVM);
                battleVM.PlayerResult = int.Parse(battleLog[battleLog.Count - 1].leftSum);
                battleVM.OponentResult = int.Parse(battleLog[battleLog.Count - 1].rightSum);
                battleVM.OponentNick = _userService.GetUserNickById(oponentId);
                battleVM.PlayerNick = _userService.GetUserNickByIdentityName();

                battleVM.battleLog = battleLog;

                var invitedEmail = _userService.GetUserEmailById(oponentId);
                _notificationService.AddBattleNotification(invitedEmail);
                NotificationHub.AddNotification(invitedEmail);
            }
            if (tuple.Item1)
                battleVM.isEnoughLife = true;
            else
                battleVM.isEnoughLife = false;

            if (tuple.Item2)
                battleVM.isEnoughEnergy = true;
            else
                battleVM.isEnoughEnergy = false;


            return View("Battle", battleVM);
        }

        public ActionResult VsSelectedPlayer(string oponentNick)
        {
            var tuple = _characterService.CheckLifeAndEnergy();
            BattleViewModel battleVM = _complementVMService.ComplementBattleVM();
            _battleService.CheckChosenAttacks(ref battleVM);

            if (tuple.Item1 && tuple.Item2 && battleVM.isAttacksChosen)
            {
                var id = _userService.GetUserIdByNick(oponentNick);

                var listOfAttacks = _battleService.BattleVsPlayer(id);
                var battleLog = _battleService.GenerateBattleText(listOfAttacks);
                _characterService.ChangeStats(battleLog, false, id);

                _complementVMService.UpdateBattleVM(ref battleVM);
                battleVM.PlayerResult = int.Parse(battleLog[battleLog.Count - 1].leftSum);
                battleVM.OponentResult = int.Parse(battleLog[battleLog.Count - 1].rightSum);
                battleVM.OponentNick = _userService.GetUserNickById(id);
                battleVM.PlayerNick = _userService.GetUserNickByIdentityName();

                battleVM.battleLog = battleLog;

                var invitedEmail = _userService.GetUserEmailById(id);
                _notificationService.AddBattleNotification(invitedEmail);
                NotificationHub.AddNotification(invitedEmail);
            }
            if (tuple.Item1)
                battleVM.isEnoughLife = true;
            else
                battleVM.isEnoughLife = false;

            if (tuple.Item2)
                battleVM.isEnoughEnergy = true;
            else
                battleVM.isEnoughEnergy = false;


            return View("Battle", battleVM);
        }

        public ActionResult GameSettings()
        {
            GameSettingsViewModel gameSettingsVM = _complementVMService.ComplementGameSettingsVM();
            ViewBag.Exercises = _trainingRoomService.CreateExerciseList(ref gameSettingsVM);


            return View(gameSettingsVM);
        }
        [HttpPost]
        public ActionResult GameSettings(GameSettingsViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Exercises = _trainingRoomService.CreateExerciseList(ref vm);
                return View(vm);
            }

            _battleService.AddChoseAttacksToCharacter(vm);

            BattleViewModel battleVM = _complementVMService.ComplementBattleVM();
            _battleService.CheckChosenAttacks(ref battleVM);

            return RedirectToAction("Home", "Home");
        }

        public ActionResult GameStyle()
        {
            GameStyleViewModel GameStyleVM = _complementVMService.ComplementGameStyleVM();

            return View(GameStyleVM);
        }
        [HttpPost]
        public void GameStyle(string value)
        {
            _battleService.ChangeStyleValue(value);
        }
    }
}

BasketBallMVC/BasketBallMVC/Controllers/TreningController.cs
using BasketBallMVC.Services;
using BasketBallMVC.ViewModel;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Web.Mvc;

namespace BasketBallMVC.Controllers
{
    [Authorize]
    public class TreningController : Controller
    {
        private ComplementViewModelsService _complementVMService = new ComplementViewModelsService();
        private TrainingRoomService _trainingRoomService = new TrainingRoomService();
        private UserService _userService = new UserService();
        // GET: Trening
        public ActionResult TrainingRoom()
        {
            TrainingRoomViewModel trainingRoomVM = _complementVMService.ComplementTrainingRoomVM();

            return View(trainingRoomVM);
        }

        public JsonResult GetExerciseCategories(string distance)
        {
            var json = _trainingRoomService.GetExerciseCategories(distance);
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetExerciseData(string exerciseName)
        {
            string json = _trainingRoomService.GetExerciseData(exerciseName);
            return Json(json, JsonRequestBehavior.AllowGet);
        }
        public JsonResult StartTraining(string btnId, string exerciseName)
        {
            Dictionary<string, string> resultDictionary = new Dictionary<string, string>();
            bool isBusy = _userService.GetCurrentUserCharacter().IsBusy;
            if (isBusy)
            {
                resultDictionary.Add("Status", "Busy");
            }
            else
            {
                bool isSuccess = _trainingRoomService.StartTraining(btnId, exerciseName);
                if (isSuccess)
                {
                    resultDictionary.Add("Status", "Ok");
                }
                else
                {
                    resultDictionary.Add("Status", "Missing");
                }
            }

            string json = JsonConvert.SerializeObject(resultDictionary);
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public void CancelTraining(string btnId, string exerciseName)
        {
            _trainingRoomService.CancelTraining(btnId, exerciseName);
        }
    }


}

BasketBallMVC/BasketBallMVC/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>Profil</title>
    @Styles.Render("~/bundles/Layout")
    @RenderSection("Styles", false)

    <meta charset="utf-8" />
</head>
<body>
    <nav class="navbar navbar-inverse sidebar" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @using (Html.BeginForm("Logoff", "Account", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <button class="navbar-brand logoffBtn">Wyloguj</button>
                }
            </div>
            <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Home", "Home")">Strona startowa<span class="menuFont pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
                    <li><a href="@Url.Action("Users", "Admin")">Użytkownicy<span class="pull-right hidden-xs showopacity glyphicon glyphicon-user menuFont"></span></a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="main">
        <!--moje-->

        <div>
            @RenderBody()
        </div>

        <footer class="navbar-fixed-bottom footer">
            
            <div id="footer-cd-logo">
                <img src="~/Content/Images/footer-cd.png" />
            </div>

            <div id="footer-copyright">
                Copyright &copy; 2016 BasketBall
            </div>
        </footer>
    </div>
    @Scripts.Render("~/Scripts/LayoutScripts")
    <script src="~/signalr/hubs"></script>
    @RenderSection("ScriptBottom", required: false)
</body>
</html>

BasketBallMVC/BasketBallMVC/Views/Shared/_Layout.cshtml
@model BasketBallMVC.ViewModel.LayoutViewModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title></title>
    @Styles.Render("~/bundles/Layout")
    @RenderSection("Styles", false)

    <meta charset="utf-8" />
</head>
<body>
    <nav class="navbar navbar-inverse sidebar" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @using (Html.BeginForm("Logoff", "Account", FormMethod.Post))
                {
                    <button class="navbar-brand logoffBtn">Wyloguj</button>
                }
            </div>
            <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Home", "Home")">Strona startowa<span class="menuFont pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
                    <li><a id="Messages" href="@Url.Action("MessageList", "Messages")">Wiadomości<span class="pull-right hidden-xs showopacity glyphicon glyphicon-envelope menuFont"></span></a></li>
                    <li><a href="@Url.Action("TrainingRoom", "Trening")">Sala Treningowa<span class="pull-right hidden-xs showopacity glyphicon glyphicon-scale menuFont"></span></a></li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle menuFont" data-toggle="dropdown">Gracze<span class="caret"></span><span class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span></a>
                        <ul class="dropdown-menu forAnimate" role="menu">
                            <li><a href="@Url.Action("Ranking", "Character")">Ranking</a></li>
                            <li class="divider"></li>
                            <li><a href="@Url.Action("FriendsList", "Character")">Znajomi</a></li>

                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle menuFont" data-toggle="dropdown">Mecz <span class="caret"></span><span class="pull-right hidden-xs showopacity glyphicon glyphicon-flag"></span></a>
                        <ul class="dropdown-menu forAnimate" role="menu">
                            <li><a href="@Url.Action("VsRandomPlayer", "Game")">Losowy przeciwnik</a></li>
                            <li class="divider"></li>
                            <li><a href="@Url.Action("VsComputer", "Game")">Gracz-komputer</a></li>
                            <li class="divider"></li>
                            <li><a href="@Url.Action("GameSettings", "Game")">Ustawienia meczu</a></li>
                            <li class="divider"></li>
                            <li><a href="@Url.Action("GameStyle", "Game")">Styl gry</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle menuFont" data-toggle="dropdown">Miasto <span class="caret"></span><span class="pull-right hidden-xs showopacity glyphicon glyphicon-tower"></span></a>
                        <ul class="dropdown-menu forAnimate" role="menu">
                            <li><a href="@Url.Action("Shop", "City")">Sklep</a></li>
                            <li class="divider"></li>
                            <li><a href="@Url.Action("Restaurant", "City")">Restauracja</a></li>
                        </ul>
                    </li>
                    <li><a id="Notifications" href="@Url.Action("NotificationList", "Notifications")">Powiadomienia<span class="pull-right hidden-xs showopacity glyphicon glyphicon-info-sign menuFont"></span></a></li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li><a id="Notifications" href="@Url.Action("Users", "Admin")">Administracja<span class="pull-right hidden-xs showopacity glyphicon glyphicon-cog menuFont"></span></a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="main">
        <div class="row">
            <div class="col-md-12" id="topBar">
                <br />
                <div id="topBarStats" class="col-md-3 col-xs-12">
                    <p class="col-md-12" id="mainTextTopBar">@Model.Name</p>
                    <p class="col-md-6 stats_main">Gold: @Model.Gold</p>
                    <p class="col-md-6 stats_main">Level: @Model.Level</p>
                    <p class="col-md-12 stats_main" style="text-align:center"> <div id="countdown"></div></p>
                </div>
                <div class="container col-md-9 col-xs-12 marginTop20">
                    <div class="row">
                        <span class="glyphicon glyphicon-heart floatLeft"> &nbsp;</span>
                        <div class="progress">
                            <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: @Model.HealthInPercent%">
                                <span class="sr-only">100% Complete (success)</span>
                            </div>
                            <span class="progress-completed">@Model.HealthInPercent%</span>
                        </div>
                        <span class="glyphicon glyphicon-adjust floatLeft"> &nbsp;</span>
                        <div class="progress">
                            <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: @Model.EnergyInPercent%">
                                <span class="sr-only">100% Complete (success)</span>
                            </div>
                            <span class="progress-completed">@Model.EnergyInPercent%</span>
                        </div>
                        <span class="glyphicon glyphicon-asterisk floatLeft"> &nbsp;</span>
                        <div class="progress">
                            <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: @Model.LevelInPercent%">
                                <span class="sr-only">100% Complete (success)</span>
                            </div>
                            <span class="progress-completed">@Model.LevelInPercent%</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div>
            @RenderBody()
        </div>

        <footer class="navbar-fixed-bottom footer">
            <div id="footer-cd-logo">
                <img src=@Url.Content("~/Content/Images/footer-cd.png") />
            </div>
            <div id="footer-copyright">
                Copyright &copy; 2016 BasketBall
            </div>
        </footer>
    </div>

    @Scripts.Render("~/Scripts/LayoutScripts")
    <script src="~/signalr/hubs"></script>
    @RenderSection("ScriptBottom", required: false)

    <script>
        var messageFlag = false;
        var notifyFlag = false;

        function flash(id, color, time, color2, time2) {
            document.getElementById(id).style.color = color;
            if (id == "Notifications") {
                notifi = setTimeout('flash("' + id + '","' + color2 + '",' + time2 + ',"' + color + '",' + time + ')', time);
            } else if (id == "Messages") {
                message = setTimeout('flash("' + id + '","' + color2 + '",' + time2 + ',"' + color + '",' + time + ')', time);
            }
        }

        $(function () {
            var notificationHub = $.connection.notificationHub;
            $.connection.hub.start().done(function () { });

            notificationHub.client.message = function () {
                if (!messageFlag) {
                    flash("Messages", "red", 500, "#9d9d9d", 500);
                    messageFlag = true;
                }
            }


            notificationHub.client.notify = function () {
                if (!notifyFlag) {
                    flash("Notifications", "red", 500, "#9d9d9d", 500);
                    notifyFlag = true;
                }

            }
            notificationHub.client.message = function () {
                if (!messageFlag) {
                    flash("Messages", "red", 500, "#9d9d9d", 500);
                    messageFlag = true;
                }
            }
            notificationHub.client.logout = function () {
                bootbox.alert("Zostałeś zabokowany przez administratora!");
                $.post('/Account/Logoff');
            }

            @{if (Model.Notifications == true)
                {
                   @: flash("Notifications", "red", 500, "#9d9d9d", 500);
                               @:notifyFlag = true;
                            }
            }
            @{if (Model.Messages == true)
            {
                @: flash("Messages", "red", 500, "#9d9d9d", 500);
                            @:messageFlag = true;
                        }
            }
        })

    </script>

</body>
</html>

BasketBallMVC/BasketBallMVC/Views/Shared/_StartingPageLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Home</title>
    <meta charset="utf-8" />
    @Styles.Render("~/bundles/startingPage")
</head>
<body class="center row" >
    <div class="col-xs-12">
        <header>
            <img src="../Content/Images/Banner.png" class="center" style="max-width:100%" />
        </header>

        <div class="col-xs-12">
            @RenderBody()
        </div>

        <img id="homeLogo" src="../Content/Images/HomeLogo.png" />

        <footer class="navbar-fixed-bottom footer">
            <div id="footer-cd-logo">
                <img src="../Content/Images/footer-cd.png" />
            </div>
            <div id="footer-copyright">
                Copyright &copy; 2016 BasketBall
            </div>
        </footer>
    </div>

    @RenderSection("ScriptBottomStartingPage", required: false)
</body>
</html>